; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:megaatmega2560]
[env:uno]
platform = atmelavr
;board = megaatmega2560
board = uno
framework = arduino


;[platformio]
; Set global library extra directories for IMBEL projects
;lib_extra_dirs = 
;    D:\MY-WORKSPACES\Arduino\MyProjects\libraries


; Way for home projects
;lib_extra_dirs = 
;     E:\Arquivo de programas\Arduino 2.0\Arduino IDE\libraries\libraries\U8glib\






