; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sparkfun_megapro16MHz]
platform = atmelavr
;board = uno
;board = pro16MHzatmega328   ; Arduino Pro/Pro Mini 16 MHz (ATmega328P)
board = sparkfun_megapro16MHz
;board = diecimila
framework = arduino
description = Projeto Teste
upload_port = COM6
monitor_speed = 9600
upload_speed = 115200
;upload_speed = 230400
upload_protocol = arduino
;upload_protocol = stk500v1
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L
upload_flags = -V

[platformio]
lib_extra_dirs = 
    D:\MY-WORKSPACES\Arduino\MyProjects\libraries




;extra_scripts = pre:wait.py

